### PR TITLE
Dashboard and home page

### PR DESCRIPTION
**Pull request by mcculloughcm**
Hey @lmeerkatz , this is a work in progress, but I opened a PR in case you wanted a better home page for the demo tomorrow. Here's a screenshot:
CleanShot 2024-07-25 at 15 50 32

I probably won't have more time to work on it until next week.

### CODE REVIEW

**Comment by lmeerkatz** [comment]
Hey @mcculloughcm - I'm seeing this error on the feature test build: 

```Error: CustomApplication(Volunteers) Home_Page_Default does not exist or is not 
a valid override for action Tab., Details: Volunteers: Home_Page_Default does 
not exist or is not a valid override for action Tab.`
```

Is there another file you need to commit?

**Comment by mcculloughcm** [comment]
Hey @lmeerkatz : I see two issues:
- I missed a new List View I created for the home page, but I can't for the life of me figure out how to pull it down. It shows up when I run `sf project retrieve preview` but when I try to actually retrieve, I get "Warning: nothing retrieved". I also tried adding it to the manifest and pulling it down that way, but same deal.
- Separately: when I run a retrieve, it says it's ignoring Flexipage:Home_Page_Default based on the .forceignore file. I'm guessing that's causing the error you're seeing. Maybe I should create a new home page instead of editing the default?

If you have a few minutes tomorrow, maybe we can jump on Zoom? I'm open until 12:30 and after 4:30. Otherwise I'll probably try re-creating the home page and list view tomorrow.

**Comment by lmeerkatz** [comment]
@mcculloughcm Sent you an invite to talk later today. I think adding a new home page instead of modifying the default is a good idea if we want to include it in the packaged components.

**Comment by mcculloughcm** [comment]
ok @lmeerkatz we're in business. I'm still not able to retrieve that list view, even after recreating it in a new scratch org, so just created the XML file by hand. But it works, so ¯\_(ツ)_/¯

**Comment by lmeerkatz** [comment]
Screenshot 2024-08-13 at 2 21 31 PM

@mcculloughcm This looks good. I replaced the gauge components with metrics since the gauges look a little dated to me, but otherwise I'm going to run with it. (I added an [issue](https://github.com/Sundae-Shop-Consulting/Volunteers/issues/59) for the missing Volunteers This Year data, which I think is the same as the [Start Date field issue](https://github.com/Sundae-Shop-Consulting/Volunteers/issues/45) you brought up at our last call. I'll start digging into that after I merge this.)

**Review by lmeerkatz — APPROVED** [review]

**Pull request merged**
